backend:
  name: github
  repo: Evanchengang/chenbridge-website
  branch: main

  base_url: https://chenbridge-oauth.evan-chengang-736.workers.dev
  auth_endpoint: /auth


media_folder: "images"
public_folder: "/images"


collections:


  # =========================
  # Packaging Solutions
  # =========================

  - name: solutions
    label: Packaging Solutions
    folder: content/solutions
    create: true
    slug: "{{slug}}"

    fields:

      - label: Title
        name: title
        widget: string


      - label: Description
        name: description
        widget: text


      - label: Main Image
        name: image
        widget: image
        required: false


      - label: Content
        name: body
        widget: markdown



  # =========================
  # Services
  # =========================

  - name: services
    label: Services
    folder: content/services
    create: true
    slug: "{{slug}}"

    fields:

      - label: Title
        name: title
        widget: string


      - label: Description
        name: description
        widget: text


      - label: Main Image
        name: image
        widget: image
        required: false


      - label: Content
        name: body
        widget: markdown



  # =========================
  # Homepage
  # =========================

  - name: pages
    label: Pages

    files:

      - file: content/homepage.md
        label: Homepage
        name: homepage

        fields:

          - label: Hero Title
            name: hero_title
            widget: string


          - label: Hero Description
            name: hero_desc
            widget: text


          - label: Contact Email
            name: contact_email
            widget: string
