backend:
  name: github
  repo: Evanchengang/chenbridge-website
  branch: main

  base_url: https://chenbridge-oauth.evan-chengang-736.workers.dev
  auth_endpoint: auth


media_folder: "images"
public_folder: "/images"


collections:

  - name: pages
    label: Pages

    files:

      - file: content/homepage.md
        label: Homepage
        name: homepage

        fields:

          - label: Hero Title
            name: hero_title
            widget: string

          - label: Hero Description
            name: hero_desc
            widget: text

          - label: Contact Email
            name: contact_email
            widget: string
